version: '3.3'

networks:
    devserver:
        external: false

volumes:
    gitea:
        driver: local
    postgresql:
        driver: local

services:

    gitea:
        image: gitea/gitea:1.10
        restart: always
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - DB_TYPE=postgres
            - DB_HOST=${DB_HOST}
            - DB_NAME=${GITEA_DATABASE}
            - DB_USER=${GITEA_USER}
            - DB_PASSWD=${GITEA_PASSWORD}
        networks:
            - devserver
        volumes:
            - gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "3000:3000"
            - "522:22"
        depends_on:
            - postgresql

#    teamcity:
#        image: jetbrains/teamcity-server
#        ports:
#            - "8112:8111"
#        volumes:
#            - ./teamcity/data:/data/teamcity_server/datadir
#            - ./teamcity/logs:/opt/teamcity/logs
#        networks:
#            - devserver
#
#    teamcity-agent:
#        image: jetbrains/teamcity-agent
#        environment:
#            - SERVER_URL=http://server:8111
#            - AGENT_NAME=regular_agent
#        networks:
#            - devserver

    postgresql:
        image: postgres:12
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - GITEA_DATABASE=${GITEA_DATABASE}
            - GITEA_USER=${GITEA_USER}
            - GITEA_PASSWORD=${GITEA_PASSWORD}
            - TEAMCITY_DATABASE=${TEAMCITY_DATABASE}
            - TEAMCITY_USER=${TEAMCITY_USER}
            - TEAMCITY_PASSWORD=${TEAMCITY_PASSWORD}
        networks:
            - devserver
        volumes:
            - postgresql:/var/lib/postgresql/data
            - ./postgresql/init.sh:/docker-entrypoint-initdb.d/init.sh

    pgadmin:
        image: dpage/pgadmin4:4.17
        container_name: devserver-pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "580:80"
        networks:
            - devserver
        restart: unless-stopped